### ISSUE TITLE
Ability to choose which optionals are synced 

### ISSUE THREAD

**Issue by JonzaUK** [rcdailey/recyclarr#44]
title says it really. :)

**Comment by rcdailey** [comment]
Yeah I really do need to get back to this. It's overdue. Thanks for the issue!

**Comment by timcoop3r** [comment]
+1 for this. would also be nice to be able to specify tag separately for the optional profile

**Comment by rcdailey** [comment]
If anyone is interested in this (or any) request (bug or feature), please give the first post a 👍🏻. That will help me prioritize, in case things get crazy :)

Thanks everyone.

**Comment by rcdailey** [comment]
Good news: This is implemented already on `master` and will be included in the upcoming 2.0 release. Stay tuned!

**Comment by JonzaUK** [comment]
Perfect, thank you :)

**Comment by rcdailey** [comment]
[v2.0 has been released](https://github.com/rcdailey/recyclarr/releases/tag/v2.0.0) and this functionality is now available. See the `include` and `exclude` sections under `filters` in the [Configuration Reference](https://github.com/rcdailey/recyclarr/wiki/Configuration-Reference#release-profile-settings)
