### ISSUE TITLE
Skip filter

### ISSUE THREAD

**Issue by ConnorJC3** [rcdailey/recyclarr#61]
Some features of the guide aren't easily expressed by a preference: see #37.

Suggestion: add a filter to skip lines from the guide's release profile, based either on content or (preferably) a regex. This should be significantly easier to implement and lets people customize what is added from the guide.

**Comment by rcdailey** [comment]
Version 2.0 is going to have filters built in. However, those filters will only be available for terms which have a Trash ID defined for them. You'll need to [contribute trash IDs for those terms](https://github.com/TRaSH-/Guides/tree/master/docs/json/sonarr) you want to customize.
