### ISSUE TITLE
Call failed with status code 400 (Bad Request)

### ISSUE THREAD

**Issue by nmbrg** [rcdailey/recyclarr#67]
Running the command `recyclarr sonarr` yields the error: 
Call failed with status code 400 (Bad Request) , check logs for full details.

I've double, and triple checked, that the Base URL and API-key are correct.

Logs:
[trash_2022-05-18_21-06-39.log](https://github.com/rcdailey/recyclarr/files/8719766/trash_2022-05-18_21-06-39.log)

**Comment by skayo** [comment]
Which version of Sonarr are you using?

**Comment by nmbrg** [comment]
you can go ahead and close this. it was a user error in the yaml.

**Comment by skayo** [comment]
You'll have to close it yourself - I'm just a contributor and wanted to help with issues, so no permissions :)
